server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: urban-ride-api-gateway

jwt:
  secret: vishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishivvishiv